sonar.projectKey=nayadev_seal_ui_react
sonar.organization=nayadev
sonar.projectName=seal_ui_react
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.exclusions=**/*.stories.tsx,dist/**,node_modules/**,storybook-static/**
sonar.coverage.exclusions=**/*.test.tsx,**/*.test.ts,**/*.stories.tsx,**/*.stories.ts,src/index.ts,src/tokens/**,src/App.tsx,src/main.tsx,src/vite-env.d.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
