import * as LabelPrimitive from '@radix-ui/react-label'
import { Slot } from '@radix-ui/react-slot'
import * as React from 'react'
import {
  Controller,
  FormProvider,
  useFormContext,
  type ControllerProps,
  type FieldPath,
  type FieldValues,
} from 'react-hook-form'

import { cn } from '@/lib/utils'

interface FormFieldContextValue<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
> {
  name: TName
}

interface FormItemContextValue {
  id: string
}

const SealFormFieldContext = React.createContext<FormFieldContextValue | null>(null)
const SealFormItemContext = React.createContext<FormItemContextValue | null>(null)

/**
 * Access form field state and generated IDs within a `SealFormField` + `SealFormItem` tree.
 *
 * Provides the field `id`, `name`, validation state, and the IDs used for
 * `aria-describedby` wiring between label, description, and error message.
 *
 * @throws When called outside of `<SealFormField>` or `<SealFormItem>`.
 */
export function useFormField() {
  const fieldContext = React.useContext(SealFormFieldContext)
  const itemContext = React.useContext(SealFormItemContext)
  const { getFieldState, formState } = useFormContext()

  if (!fieldContext) {
    throw new Error('useFormField must be used within <SealFormField>')
  }
  if (!itemContext) {
    throw new Error('useFormField must be used within <SealFormItem>')
  }

  const fieldState = getFieldState(fieldContext.name, formState)
  const { id } = itemContext

  return {
    id,
    name: fieldContext.name,
    formItemId: `${id}-form-item`,
    formDescriptionId: `${id}-form-item-description`,
    formMessageId: `${id}-form-item-message`,
    ...fieldState,
  }
}

/**
 * Root form context backed by React Hook Form's `FormProvider`.
 *
 * Spread the return value of `useForm()` directly as props. All
 * `SealFormField` descendants must be mounted inside this component.
 *
 * @example
 * const form = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema) })
 * return (
 *   <SealForm {...form}>
 *     <form onSubmit={(e) => { void form.handleSubmit(onSubmit)(e) }}>
 *       <SealFormField control={form.control} name="email" render={...} />
 *     </form>
 *   </SealForm>
 * )
 */
export const SealForm = FormProvider

/**
 * Connects a single field to React Hook Form's `Controller`.
 *
 * Must be a descendant of `<SealForm>` and an ancestor of `<SealFormItem>`.
 * The `render` prop receives the field's `value`, `onChange`, `onBlur`, and `ref`.
 */
export function SealFormField<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
>(props: ControllerProps<TFieldValues, TName>) {
  return (
    <SealFormFieldContext.Provider value={{ name: props.name }}>
      <Controller {...props} />
    </SealFormFieldContext.Provider>
  )
}

/**
 * Container for a single form field — label, control, description, and message.
 *
 * Generates a stable `id` shared between `SealFormLabel`, `SealFormControl`,
 * `SealFormDescription`, and `SealFormMessage` to establish ARIA relationships.
 */
export const SealFormItem = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  function SealFormItem({ className, ...props }, ref) {
    const id = React.useId()
    return (
      <SealFormItemContext.Provider value={{ id }}>
        <div
          ref={ref}
          className={cn('flex flex-col gap-[var(--seal-dimension-xs)]', className)}
          {...props}
        />
      </SealFormItemContext.Provider>
    )
  },
)
SealFormItem.displayName = 'SealFormItem'

/**
 * Accessible label for the form control.
 *
 * Automatically receives `--seal-semantic-error` color when the field has a
 * validation error, and `--seal-text-secondary` otherwise. Linked to the
 * control via `htmlFor` using the ID generated by `SealFormItem`.
 */
export const SealFormLabel = React.forwardRef<
  React.ComponentRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>
>(function SealFormLabel({ className, style, ...props }, ref) {
  const { error, formItemId } = useFormField()

  return (
    <LabelPrimitive.Root
      ref={ref}
      htmlFor={formItemId}
      className={cn('leading-none', className)}
      style={{
        fontSize: 'var(--seal-style-small-font-size)',
        fontWeight: 'var(--seal-style-small-font-weight)',
        color: error ? 'var(--seal-semantic-error)' : 'var(--seal-text-secondary)',
        ...style,
      }}
      {...props}
    />
  )
})
SealFormLabel.displayName = 'SealFormLabel'

/**
 * Wraps the actual input control (e.g. `SealTextField`, `SealCheckbox`) and
 * connects it to its `SealFormItem` via `id`, `aria-describedby`, and `aria-invalid`.
 *
 * Uses a Radix `Slot` so the child receives the ARIA props directly.
 */
export const SealFormControl = React.forwardRef<
  React.ComponentRef<typeof Slot>,
  React.ComponentPropsWithoutRef<typeof Slot>
>(function SealFormControl(props, ref) {
  const { error, formItemId, formDescriptionId, formMessageId } = useFormField()

  return (
    <Slot
      ref={ref}
      id={formItemId}
      aria-describedby={error ? `${formDescriptionId} ${formMessageId}` : formDescriptionId}
      aria-invalid={!!error}
      {...props}
    />
  )
})
SealFormControl.displayName = 'SealFormControl'

/**
 * Optional helper text rendered below the form control.
 *
 * Linked to the control via `aria-describedby`. Use to describe the expected
 * format or constraints without duplicating information from the label.
 */
export const SealFormDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(function SealFormDescription({ className, style, ...props }, ref) {
  const { formDescriptionId } = useFormField()

  return (
    <p
      ref={ref}
      id={formDescriptionId}
      className={cn(className)}
      style={{
        fontSize: 'var(--seal-style-caption-font-size)',
        fontWeight: 'var(--seal-style-caption-font-weight)',
        lineHeight: 'var(--seal-style-caption-line-height)',
        color: 'var(--seal-text-secondary)',
        ...style,
      }}
      {...props}
    />
  )
})
SealFormDescription.displayName = 'SealFormDescription'

/**
 * Validation error message for the enclosing `SealFormField`.
 *
 * When the field has a react-hook-form error, the error message takes
 * precedence over any `children`. Renders nothing when neither source provides
 * content. Announced immediately to screen readers via `role="alert"`.
 */
export const SealFormMessage = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(function SealFormMessage({ className, style, children, ...props }, ref) {
  const { error, formMessageId } = useFormField()
  const body = error ? (error.message ?? '') : children

  if (!body) return null

  return (
    <p
      ref={ref}
      id={formMessageId}
      role="alert"
      className={cn(className)}
      style={{
        fontSize: 'var(--seal-style-caption-font-size)',
        fontWeight: 'var(--seal-style-caption-font-weight)',
        lineHeight: 'var(--seal-style-caption-line-height)',
        color: 'var(--seal-semantic-error)',
        ...style,
      }}
      {...props}
    >
      {body}
    </p>
  )
})
SealFormMessage.displayName = 'SealFormMessage'
