name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
